In [3]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split

In [4]:
columns = [i for i in range(1,61)]
columns.append("label")
df = pd.read_csv("winedatasets",delimiter = ",",names = columns,header = None)

In [5]:
df.head()

1       2       3       4       5       6       7       8       9  \
0  0.0200  0.0371  0.0428  0.0207  0.0954  0.0986  0.1539  0.1601  0.3109   
1  0.0453  0.0523  0.0843  0.0689  0.1183  0.2583  0.2156  0.3481  0.3337   
2  0.0262  0.0582  0.1099  0.1083  0.0974  0.2280  0.2431  0.3771  0.5598   
3  0.0100  0.0171  0.0623  0.0205  0.0205  0.0368  0.1098  0.1276  0.0598   
4  0.0762  0.0666  0.0481  0.0394  0.0590  0.0649  0.1209  0.2467  0.3564   

       10  ...      52      53      54      55      56      57      58  \
0  0.2111  ...  0.0027  0.0065  0.0159  0.0072  0.0167  0.0180  0.0084   
1  0.2872  ...  0.0084  0.0089  0.0048  0.0094  0.0191  0.0140  0.0049   
2  0.6194  ...  0.0232  0.0166  0.0095  0.0180  0.0244  0.0316  0.0164   
3  0.1264  ...  0.0121  0.0036  0.0150  0.0085  0.0073  0.0050  0.0044   
4  0.4459  ...  0.0031  0.0054  0.0105  0.0110  0.0015  0.0072  0.0048   

       59      60  label  
0  0.0090  0.0032      R  
1  0.0052  0.0044      R  
2  0.0095  0.0078      R  
3  0.0040  0.0117      R  
4  0.0107  0.0094      R  

[5 rows x 61 columns]

In [6]:
df["label"].replace({'wine_data': 0, 'names': 1},inplace = True)

In [7]:
X_train, X_test, y_train, y_test = train_test_split(df[columns[:-1]], df[columns[-1]], test_size=0.33, random_state=42)

In [8]:
X_train.head()

1       2       3       4       5       6       7       8       9   \
28   0.0100  0.0275  0.0190  0.0371  0.0416  0.0201  0.0314  0.0651  0.1896   
42   0.0211  0.0319  0.0415  0.0286  0.0121  0.0438  0.1299  0.1390  0.0695   
79   0.0108  0.0086  0.0058  0.0460  0.0752  0.0887  0.1015  0.0494  0.0472   
97   0.0491  0.0279  0.0592  0.1270  0.1772  0.1908  0.2217  0.0768  0.1246   
142  0.0526  0.0563  0.1219  0.1206  0.0246  0.1022  0.0539  0.0439  0.2291   

         10  ...      51      52      53      54      55      56      57  \
28   0.2668  ...  0.0118  0.0088  0.0104  0.0036  0.0088  0.0047  0.0117   
42   0.0568  ...  0.0053  0.0090  0.0042  0.0153  0.0106  0.0020  0.0105   
79   0.0393  ...  0.0161  0.0029  0.0078  0.0114  0.0083  0.0058  0.0003   
97   0.2028  ...  0.0268  0.0081  0.0129  0.0161  0.0063  0.0119  0.0194   
142  0.1632  ...  0.0380  0.0339  0.0149  0.0335  0.0376  0.0174  0.0132   

         58      59      60  
28   0.0020  0.0091  0.0058  
42   0.0049  0.0070  0.0080  
79   0.0023  0.0026  0.0027  
97   0.0140  0.0332  0.0439  
142  0.0103  0.0364  0.0208  

[5 rows x 60 columns]

In [9]:
y_train.head()

28     0
42     0
79     0
97     1
142    1
Name: label, dtype: int64

In [10]:
X_train = np.array(X_train)
X_test = np.array(X_test)
y_train = np.array(y_train)
y_test = np.array(y_test)

In [11]:
W = np.random.rand(60,1)
W.shape

(60, 1)

In [12]:
b = np.random.rand()
b

0.6743423274922576

In [13]:
X_train = X_train.T
X_train.shape

(60, 139)

In [14]:
Z = np.dot(W.T,X_train,) + b

In [15]:
Z

array([[ 8.07146698, 10.44725185,  7.48077217,  8.8362716 ,  9.82885868,
         7.34798334,  9.05180378,  9.69213841,  8.93280711,  7.84987635,
         9.62542211,  7.91841296,  9.25922058,  7.77173662,  7.88262301,
         8.85777098,  7.19219791, 11.44222377,  8.15743671, 10.6340658 ,
         9.95150553,  9.40418979, 11.07864376, 10.10355076,  9.86755048,
         8.37207147,  8.70780195,  8.14404987,  9.41959822,  9.26011138,
         9.60455985,  8.56656303,  6.80767316,  7.30808219,  9.49984804,
         8.80994732,  8.22923704, 10.00492003,  7.63866634, 10.22222936,
         8.51234032,  8.23985657,  9.6088502 ,  6.91988407,  8.79825727,
         6.8818994 ,  9.36427147,  6.92019201,  8.67645131,  9.46468578,
         8.65619184,  8.80234521,  8.9216093 ,  7.71436324, 10.15631412,
         5.2106519 ,  8.05052885,  7.67358947, 10.02479307, 11.10727791,
         7.98676374,  8.95692501,  8.15332575,  9.09579285,  8.55031647,
        10.03506515,  8.12425166,  8.82874029,  8.8

In [16]:
Z.shape

(1, 139)

In [17]:
Z[0,:5]

array([ 8.07146698, 10.44725185,  7.48077217,  8.8362716 ,  9.82885868])

In [18]:
def sigmoid(z):
    return 1/(1 + np.exp(-z))

In [19]:
A = [sigmoid(z) for z in Z[0]]

In [20]:
A[:5]

[0.9996877727441571,
 0.9999709729056385,
 0.9994364958374133,
 0.9998546574153567,
 0.9999461286926853]

In [21]:
A = sigmoid(Z)
A[:5]

array([[0.99968777, 0.99997097, 0.9994365 , 0.99985466, 0.99994613,
        0.99935652, 0.99988283, 0.99993824, 0.99986803, 0.99961035,
        0.99993398, 0.99963615, 0.99990478, 0.9995787 , 0.9996229 ,
        0.99985775, 0.99924813, 0.99998927, 0.99971349, 0.99997592,
        0.99995235, 0.99991763, 0.99998456, 0.99995907, 0.99994817,
        0.99976882, 0.99983474, 0.99970963, 0.99991889, 0.99990486,
        0.99993258, 0.99980967, 0.99889596, 0.99933035, 0.99992514,
        0.99985078, 0.99973333, 0.99995482, 0.99951876, 0.99996365,
        0.99979907, 0.99973615, 0.99993287, 0.99901303, 0.99984903,
        0.99897486, 0.99991427, 0.99901333, 0.99982947, 0.99992246,
        0.99982598, 0.99984964, 0.99986654, 0.99955383, 0.99996117,
        0.99457151, 0.99968117, 0.99953527, 0.99995571, 0.999985  ,
        0.99966018, 0.99987117, 0.99971231, 0.99988788, 0.99980655,
        0.99995617, 0.99970382, 0.99985356, 0.99986063, 0.99919352,
        0.99993975, 0.9999876 , 0.99979531, 0.99

In [22]:
W.shape

(60, 1)

In [23]:
X_train.shape

(60, 139)

In [24]:
Z = np.dot(W.T,X_train,) + b

In [25]:
Z.shape

(1, 139)

In [28]:
Z[0,:5]

array([ 8.07146698, 10.44725185,  7.48077217,  8.8362716 ,  9.82885868])

In [31]:
alpha = 0.01
for i in range(100):
    #forward pass
    Z = np.dot(W.T, X_train, )+b
    A = sigmoid(Z)
    A = np.where (A<0.5,0,1)
    #Backward pass
    J = log_loss(y_train,A)
    print(J)
    dz=A=y_train
    dw=np.dot(X_train,dz.T)/numOfTrainSamples
    db = np.sum(dz,axis=1)/numOfTrainSamples
    W=W- alpha*dw
    b=b-alpha *db

NameError: name 'log_loss' is not defined

In [ ]:
np.sum(dz,axis=1/numOfTrainSamples)
np.dot(X_Train,dz.T)