In [67]:
import numpy as np
import pandas as pd

import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split

In [68]:
columns=['class','Alcohol', 'Malicacid','Ash','Alcalinity of ash'  , 'Magnesium', 'Total phenols', 'Flavanoids','Nonflavanoid phenols', 'Proanthocyanins','Color intensity','Hue','OD280/OD315 of diluted wines','Proline  ']
# columns=[i for
df = pd.read_csv("wine.data",names=columns,delimiter=",")
df.head()

class  Alcohol  Malicacid   Ash  Alcalinity of ash  Magnesium  \
0      1    14.23       1.71  2.43               15.6        127   
1      1    13.20       1.78  2.14               11.2        100   
2      1    13.16       2.36  2.67               18.6        101   
3      1    14.37       1.95  2.50               16.8        113   
4      1    13.24       2.59  2.87               21.0        118   

   Total phenols  Flavanoids  Nonflavanoid phenols  Proanthocyanins  \
0           2.80        3.06                  0.28             2.29   
1           2.65        2.76                  0.26             1.28   
2           2.80        3.24                  0.30             2.81   
3           3.85        3.49                  0.24             2.18   
4           2.80        2.69                  0.39             1.82   

   Color intensity   Hue  OD280/OD315 of diluted wines  Proline    
0             5.64  1.04                          3.92       1065  
1             4.38  1.05                          3.40       1050  
2             5.68  1.03                          3.17       1185  
3             7.80  0.86                          3.45       1480  
4             4.32  1.04                          2.93        735

In [71]:
X_train, X_test, y_train, y_test = train_test_split(df[columns[1:]], df[columns[0]], test_size=0.33, random_state=42)

In [72]:
k=3


In [73]:
ran=np.random.randint(0,X_train.shape[0],k)
ran

array([ 8, 62, 61])

In [75]:
train=np.array(X_train)
train.shape

(119, 13)

In [76]:
centroids=train[ran]
centroids

array([[1.225e+01, 3.880e+00, 2.200e+00, 1.850e+01, 1.120e+02, 1.380e+00,
        7.800e-01, 2.900e-01, 1.140e+00, 8.210e+00, 6.500e-01, 2.000e+00,
        8.550e+02],
       [1.351e+01, 1.800e+00, 2.650e+00, 1.900e+01, 1.100e+02, 2.350e+00,
        2.530e+00, 2.900e-01, 1.540e+00, 4.200e+00, 1.100e+00, 2.870e+00,
        1.095e+03],
       [1.184e+01, 2.890e+00, 2.230e+00, 1.800e+01, 1.120e+02, 1.720e+00,
        1.320e+00, 4.300e-01, 9.500e-01, 2.650e+00, 9.600e-01, 2.520e+00,
        5.000e+02]])

In [77]:
def update_assignments(data, centroids):   
    c = []
    for i in data:
        c.append(np.argmin(np.sum((i.reshape((1, 13)) - centroids) ** 2, axis=1)))
#         print(c)
    return c

In [78]:
def update_centroids(data, num_clusters, assignments):
    cen = []
    for c in range(len(num_clusters)):
        cen.append(np.mean([data[x] for x in range(len(data)) if assignments[x] == c], axis=0))
    return cen

In [79]:
data =np.array(X_train)
print(data.shape)
data

(119, 13)


array([[1.371e+01, 1.860e+00, 2.360e+00, ..., 1.110e+00, 4.000e+00,
        1.035e+03],
       [1.388e+01, 5.040e+00, 2.230e+00, ..., 5.800e-01, 1.330e+00,
        4.150e+02],
       [1.229e+01, 1.410e+00, 1.980e+00, ..., 1.230e+00, 2.740e+00,
        4.280e+02],
       ...,
       [1.438e+01, 1.870e+00, 2.380e+00, ..., 1.200e+00, 3.000e+00,
        1.547e+03],
       [1.269e+01, 1.530e+00, 2.260e+00, ..., 9.600e-01, 2.060e+00,
        4.950e+02],
       [1.234e+01, 2.450e+00, 2.460e+00, ..., 8.000e-01, 3.380e+00,
        4.380e+02]])

In [80]:
for i in range(100):
    a = update_assignments(data, centroids)
    centroids = update_centroids(data, centroids, a)
    centroids = np.array(centroids)

In [81]:
 def euclidian_distance(query,X):
        Sub=X-np.array(query)
        sqr=np.square(Sub)
        add=np.sum(sqr,axis=1)
        dis=np.sqrt(add)
        return dis

In [82]:
 def test(query,centtroids):
        euclidian_distance(query,centroids)
        near=np.argsort(dis)[:self.k]

In [83]:
centroids
X_test

Alcohol  Malicacid   Ash  Alcalinity of ash  Magnesium  Total phenols  \
19     13.64       3.10  2.56               15.2        116           2.70   
45     14.21       4.04  2.44               18.9        111           2.85   
140    12.93       2.81  2.70               21.0         96           1.54   
30     13.73       1.50  2.70               22.5        101           3.00   
67     12.37       1.17  1.92               19.6         78           2.11   
16     14.30       1.92  2.72               20.0        120           2.80   
119    12.00       3.43  2.00               19.0         87           2.00   
174    13.40       3.91  2.48               23.0        102           1.80   
109    11.61       1.35  2.70               20.0         94           2.74   
141    13.36       2.56  2.35               20.0         89           1.40   
24     13.50       1.81  2.61               20.0         96           2.53   
150    13.50       3.12  2.62               24.0        123           1.40   
41     13.41       3.84  2.12               18.8         90           2.45   
118    12.77       3.43  1.98               16.0         80           1.63   
15     13.63       1.81  2.70               17.2        112           2.85   
111    12.52       2.43  2.17               21.0         88           2.55   
113    11.41       0.74  2.50               21.0         88           2.48   
82     12.08       1.13  2.51               24.0         78           2.00   
9      13.86       1.35  2.27               16.0         98           2.98   
114    12.08       1.39  2.50               22.5         84           2.56   
18     14.19       1.59  2.48               16.5        108           3.30   
66     13.11       1.01  1.70               15.0         78           2.98   
60     12.33       1.10  2.28               16.0        101           2.05   
169    13.40       4.60  2.86               25.0        112           1.98   
171    12.77       2.39  2.28               19.5         86           1.39   
164    13.78       2.76  2.30               22.0         90           1.35   
117    12.42       1.61  2.19               22.5        108           2.00   
65     12.37       1.21  2.56               18.1         98           2.42   
90     12.08       1.83  2.32               18.5         81           1.60   
55     13.56       1.73  2.46               20.5        116           2.96   
29     14.02       1.68  2.21               16.0         96           2.65   
128    12.37       1.63  2.30               24.5         88           2.22   
145    13.16       3.57  2.15               21.0        102           1.50   
31     13.58       1.66  2.36               19.1        106           2.86   
12     13.75       1.73  2.41               16.0         89           2.60   
42     13.88       1.89  2.59               15.0        101           3.25   
158    14.34       1.68  2.70               25.0         98           2.80   
137    12.53       5.51  2.64               25.0         96           1.79   
98     12.37       1.07  2.10               18.5         88           3.52   
159    13.48       1.67  2.64               22.5         89           2.60   
38     13.07       1.50  2.10               15.5         98           2.40   
108    12.22       1.29  1.94               19.0         92           2.36   
85     12.67       0.98  2.24               18.0         99           2.20   
68     13.34       0.94  2.36               17.0        110           2.53   
143    13.62       4.95  2.35               20.0         92           2.00   
2      13.16       2.36  2.67               18.6        101           2.80   
100    12.08       2.08  1.70               17.5         97           2.23   
122    12.42       4.43  2.73               26.5        102           2.20   
154    12.58       1.29  2.10               20.0        103           1.48   
51     13.83       1.65  2.60               17.2         94           2.45   
76     13.03       0.90  1.

In [58]:
if __name__ == "__main__":
    print("hello")

hello
