### **TASK 1**
Use the implementation of perceptron from the last lab manual and model the truth table of XOR.

![XOR](./XOR.png "XOR")


### **TASK 2**
1. Import the diabetes dataset. You can find data description in the description file.
2. Use pandas plots to have a look and feel of the different attributes of the data.
3. Apply perceptron algorithm to model the data distribution.
4. Use mean squared error as your cost/ error function.
5. Use the below given derivatives to find gradients of each W.

![MSE](./MSE.png "MSE")

![MSE derivative](./derivativeMSE.png "MSE derivative")


In [180]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split

In [181]:
X = np.array([[0, 0, 1, 1], [0, 1, 0, 1]]) 
Y = np.array([[0, 1, 1, 0]])
Y=Y[0]
Y

array([0, 1, 1, 0])

In [182]:
print ("Features")
print(X)
print("Labels")
print(Y)

Features
[[0 0 1 1]
 [0 1 0 1]]
Labels
[0 1 1 0]


In [189]:
X=X.T

In [190]:
X.shape

(2, 4)

In [185]:
W= np.random.rand(2,1)
b=np.random.rand()

In [186]:
print(W)
print(b)

[[0.46288898]
 [0.61519807]]
0.4907507749755249


In [187]:
def sigmoid(z):
    return 1/(1 + np.exp(-z))

In [188]:
from sklearn.metrics import log_loss
J = log_loss(Y,A)

ValueError: Found input variables with inconsistent numbers of samples: [2, 4]

In [ ]:
J

In [193]:
alpha = 0.01
for i in range(100):
    #forward pass
    Z = np.dot(W.T,X) + b
    A = sigmoid(Z)
    A = np.where (A<0.5,0,1)
    A=A.squeeze()
    #Backward pass
    J = log_loss(Y,A)
    #print(J)
    dz=A-Y
    dw=np.expand_dims(dz,axis=0)
    dw=np.dot(X,dz.T)/4
    db = np.sum(dz,axis=0)/X.shape[0]
    W=W- alpha*dw
    b=b-alpha *db

ValueError: Found input variables with inconsistent numbers of samples: [2, 4]

In [192]:
print(A)
print(Y)

[[1 1 1 1]
 [1 1 1 1]]
[0 1 1 0]


In [2]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split

In [5]:
columns = [i for i in range(1,10)]
columns.append("label")
df = pd.read_csv("diabetes.txt",delimiter = ",",names = columns,header = None)

In [6]:
df.head()

1   2   3   4   5   6   7  \
0       AGE\tSEX\tBMI\tBP\tS1\tS2\tS3\tS4\tS5\tS6\tY NaN NaN NaN NaN NaN NaN   
1  59\t2\t32.1\t101\t157\t93.2\t38\t4\t4.8598\t87... NaN NaN NaN NaN NaN NaN   
2  48\t1\t21.6\t87\t183\t103.2\t70\t3\t3.8918\t69... NaN NaN NaN NaN NaN NaN   
3  72\t2\t30.5\t93\t156\t93.6\t41\t4\t4.6728\t85\... NaN NaN NaN NaN NaN NaN   
4  24\t1\t25.3\t84\t198\t131.4\t40\t5\t4.8903\t89... NaN NaN NaN NaN NaN NaN   

    8   9  label  
0 NaN NaN    NaN  
1 NaN NaN    NaN  
2 NaN NaN    NaN  
3 NaN NaN    NaN  
4 NaN NaN    NaN

In [ ]:
alpha = 0.01
for i in range(100):
    #forward pass
    Z = np.dot(W.T,X) + b
    #A = sigmoid(Z)
    A = np.where (A<0.5,0,1)
    A=A.squeeze()
    #Backward pass
    J = log_loss(Y,A)
    #print(J)
    dz=A-Y
    dw=np.expand_dims(dz,axis=0)
    dw=np.dot(X,dz.T)/4
    db = np.sum(dz,axis=0)/4
    W=W- alpha*dw
    b=b-alpha *db